project:
  type: website
  output-dir: docs

website:
  title: "COVID-19 & Health Indicators Analysis"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: EDA
      - href: models.qmd
        text: Models
      - href: results.qmd
        text: Results

execute:
  echo: false
  message: false
  warning: false

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
