project:
  type: website
  output-dir: docs

website:
  title: "HIV and Health Indicators Analysis"

execute:
  echo: false
  message: false
  warning: false

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    css: styles.css
