project:
  type: website
  output-dir: docs

website:
  title: "HIV and Health Indicators Analysis"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home

execute:
  echo: false
  message: false
  warning: false

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
